data_start:
	db 0,  0x1b, '1', '2', '3', '4', '5', '6', '7', '8'
	db '9', '0', '[', ']', 0x8,
	db 0x9,
	db "'", ',', '.', 'p',
	db 'y', 'f', 'g', 'c', 'r', 'l', '/', '=', 0xa,
	db 0,
	db 'a', 'o', 'e', 'u', 'i', 'd', 'h', 't', 'n', 's',
	db "-", '`',   0,
	db '\', ';', 'q', 'j', 'k', 'x', 'b',
	db 'm', 'w', 'v', 'z',   0,
	db '*',
	db 0,
	db ' ',
	db 0,
	db 0,
	db 0,   0,   0,   0,   0,   0,   0,   0,
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,
	db '[',
	db 0,
	db 0,
	db 0,
	db ']',
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,   0,   0,
	db 0,
	db 0,
	db 0,	; All other keys are undefined
data_end:
	times 128 - (data_end-data_start) db 0
