data_start:
	db 0,  0x1b, '1', '2', '3', '4', '5', '6', '7', '8'
	db '9', '0', '-', '=', 0x8,
	db 0x9,
	db 'q', 'w', 'e', 'r',
	db 't', 'y', 'u', 'i', 'o', 'p', '[', ']', 0xa,
	db 0,
	db 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';',
	db "'", '`',   0,
	db '\', 'z', 'x', 'c', 'v', 'b', 'n',
	db 'm', ',', '.', '/',   0,
	db '*',
	db 0,
	db ' ',
	db 0,
	db 0,
	db 0,   0,   0,   0,   0,   0,   0,   0,
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,
	db '-',
	db 0,
	db 0,
	db 0,
	db '+',
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,
	db 0,   0,   0,
	db 0,
	db 0,
	db 0,	; All other keys are undefined
data_end:
	times 128 - (data_end-data_start) db 0
